---
to: <%= h.src() %>/<%= h.changeCase.lower(name) %>/js/states.js
---
/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
(($) => {
  $(document).on('state:disabled', (e) => {
    if (e.trigger) {
      $(e.target)
        .closest('button.js-form-submit')
        .toggleClass('form-disabled', e.value)
        .prop('disabled', e.value);
    }
  });
})(jQuery);
