---
to: "<%= has_storybook ? `${h.src()}/${h.changeCase.lower(name)}/templates/components/suggestions/a-image/config.styles.yml` : null %>"
---
# This is yml configuration where all image styles should be defined from the
# entire design system.
#
# ~95% of all images on the web-site usually have image effect "scale and crop".
# ~5% are about "scale". Sometimes these values can be different (like 60/40,
# depending on the web-site of course, but still!).
# ~0.000001% other cases have other image effects (or more than 1 image effect
# per image). Usually it's focal-points image effects or something like this,
# and we can ignore it in storybook, because we are using fake images for preview.
#
# Idea of this file is next:
#   1. Prepare yml file with all image styles described
#   2. Then, backender can write some little script, which can grab all image
#      styles from here and generate configs for drupal automatically.
#      Depending on the site needs of course, but usually on large web-sites we
#      can have hundreds of image styles. So it becomes hard to manually create
#      them in drupal -> this is where this idea can help, just to automate
#      processes and save time.
#   3. It's a specification of all image styles from design system, located in
#      one place.
#
# We don't want to go very deep in the settings, like provide setting for focal
# points, or "allow upscale" property for "scale" effect, or other. It's all so
# rare cases and for sure it can be manually configured in drupal if needed.
#
# The following examples are "default" - just to show you how you can use this
# config file.
1000_x_400_scale_and_crop:
  label: 1000 x 400 (Scale and crop)
  effect: image_scale_and_crop
  width: 1000
  height: 400
500_x_200_scale_and_crop:
  label: 500 x 200 (Scale and crop)
  effect: image_scale_and_crop
  width: 500
  height: 200
auto_x_120_scale:
  label: Auto x 120 (Scale)
  effect: image_scale
  width: auto
  height: 120
80_x_80_scale:
  label: 80 x 80 (Scale)
  effect: image_scale
  width: 80
  height: 80
auto_x_60_scale:
  label: Auto x 60 (Scale)
  effect: image_scale
  width: auto
  height: 60
40_x_40_scale:
  label: 40 x 40 (Scale)
  effect: image_scale
  width: 40
  height: 40
# Why do you see 1_x_1 image style here?
# That's a little trick for responsive image groups, where image for example
# can be hidden on some breakpoint. And when image is hidden - we can set it
# to use 1_x_1 image style. In that case browser will download just few bytes
# (because of 1px image).
1_x_1_fallback:
  label: 1 x 1 (Fallback)
  effect: image_scale_and_crop
  width: 1
  height: 1
